version: '3.8'

services:
  # Next.js Web Application
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      # For development, mount source code for hot reload
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
    depends_on:
      - oracle
    networks:
      - pcm-network

  # Oracle Database
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=${ORACLE_PWD:-PCMSystem123}
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./infrastructure/oracle/init:/docker-entrypoint-initdb.d
    networks:
      - pcm-network
    healthcheck:
      test: ["CMD", "sqlplus", "-s", "sys/$$ORACLE_PWD@localhost:1521/xe as sysdba", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:
    driver: local

networks:
  pcm-network:
    driver: bridge