-- PCM Project Database Schema Extension - Role Permission System
-- Story 2-2: Add PERMISSIONS and ROLE_PERMISSIONS tables

-- Drop tables if they exist (for development purposes)
DROP TABLE IF EXISTS ROLE_PERMISSIONS CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS PERMISSIONS CASCADE CONSTRAINTS;

-- 權限表
CREATE TABLE PERMISSIONS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL UNIQUE,
    description NVARCHAR2(500),
    resource VARCHAR2(255),
    action VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 角色權限關聯表
CREATE TABLE ROLE_PERMISSIONS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id NUMBER NOT NULL,
    permission_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES ROLES(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES PERMISSIONS(id) ON DELETE CASCADE,
    UNIQUE(role_id, permission_id)
);

-- Create indexes for better performance
CREATE INDEX idx_permissions_name ON PERMISSIONS(name);
CREATE INDEX idx_permissions_resource ON PERMISSIONS(resource);
CREATE INDEX idx_permissions_action ON PERMISSIONS(action);
CREATE INDEX idx_role_permissions_role_id ON ROLE_PERMISSIONS(role_id);
CREATE INDEX idx_role_permissions_permission_id ON ROLE_PERMISSIONS(permission_id);

COMMIT;