-- PCM Project Permission System Seed Data
-- Story 2-2: Add permissions and role-permission mappings

-- Clear existing permission data (for development purposes)
DELETE FROM ROLE_PERMISSIONS;
DELETE FROM PERMISSIONS;

-- Reset sequences
ALTER TABLE PERMISSIONS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE ROLE_PERMISSIONS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

-- Insert Base Permissions
-- Project Management Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('project.read', '檢視專案資訊', 'project', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('project.write', '編輯專案資訊', 'project', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('project.delete', '刪除專案', 'project', 'delete');

-- WBS Management Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('wbs.read', '檢視工作分解結構', 'wbs', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('wbs.write', '編輯工作分解結構', 'wbs', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('wbs.delete', '刪除工作分解結構項目', 'wbs', 'delete');

-- Personnel Management Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('personnel.read', '檢視人員資訊', 'personnel', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('personnel.write', '編輯人員資訊', 'personnel', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('personnel.delete', '刪除人員資訊', 'personnel', 'delete');

-- Report Management Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('reports.read', '檢視報告', 'reports', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('reports.write', '建立/編輯報告', 'reports', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('reports.delete', '刪除報告', 'reports', 'delete');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('reports.approve', '審核報告', 'reports', 'approve');

-- Announcement Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('announcements.read', '檢視公告', 'announcements', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('announcements.write', '建立/編輯公告', 'announcements', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('announcements.delete', '刪除公告', 'announcements', 'delete');

-- Duty Roster Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('duty.read', '檢視值班表', 'duty', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('duty.write', '編輯值班表', 'duty', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('duty.delete', '刪除值班記錄', 'duty', 'delete');

-- Attendance Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('attendance.read', '檢視出勤記錄', 'attendance', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('attendance.write', '編輯出勤記錄', 'attendance', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('attendance.delete', '刪除出勤記錄', 'attendance', 'delete');

-- User and Role Management Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('users.read', '檢視使用者資訊', 'users', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('users.write', '編輯使用者資訊', 'users', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('roles.read', '檢視角色資訊', 'roles', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('roles.write', '編輯角色資訊', 'roles', 'write');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('roles.assign', '指派角色給使用者', 'roles', 'assign');

-- Dashboard and System Permissions
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('dashboard.read', '檢視儀表板', 'dashboard', 'read');
INSERT INTO PERMISSIONS (name, description, resource, action) VALUES 
('system.admin', '系統管理權限', 'system', 'admin');

-- Role-Permission Assignments
-- PM (Project Manager) Permissions - ID 1
INSERT INTO ROLE_PERMISSIONS (role_id, permission_id) VALUES 
(1, 1), (1, 2),   -- project read/write
(1, 4), (1, 5), (1, 6),   -- wbs read/write/delete
(1, 7), (1, 8), (1, 9),   -- personnel read/write/delete
(1, 10), (1, 11), (1, 12), (1, 13),   -- reports read/write/delete/approve
(1, 14), (1, 15), (1, 16),   -- announcements read/write/delete
(1, 17), (1, 18), (1, 19),   -- duty read/write/delete
(1, 20), (1, 21),   -- attendance read/write
(1, 23), (1, 24),   -- users read/write
(1, 25), (1, 26), (1, 27),   -- roles read/write/assign
(1, 28);   -- dashboard read

-- QC (Quality Control) Permissions - ID 2
INSERT INTO ROLE_PERMISSIONS (role_id, permission_id) VALUES 
(2, 1),   -- project read
(2, 4),   -- wbs read
(2, 7), (2, 8),   -- personnel read/write
(2, 10), (2, 11), (2, 13),   -- reports read/write/approve
(2, 14), (2, 15),   -- announcements read/write
(2, 17),   -- duty read
(2, 20), (2, 21),   -- attendance read/write
(2, 23),   -- users read
(2, 25),   -- roles read
(2, 28);   -- dashboard read

-- Supervisor (工地主任) Permissions - ID 3
INSERT INTO ROLE_PERMISSIONS (role_id, permission_id) VALUES 
(3, 1),   -- project read
(3, 4), (3, 5),   -- wbs read/write
(3, 7), (3, 8),   -- personnel read/write
(3, 10), (3, 11),   -- reports read/write
(3, 14), (3, 15),   -- announcements read/write
(3, 17), (3, 18), (3, 19),   -- duty read/write/delete
(3, 20), (3, 21), (3, 22),   -- attendance read/write/delete
(3, 23),   -- users read
(3, 25),   -- roles read
(3, 28);   -- dashboard read

-- Engineer Permissions - ID 4
INSERT INTO ROLE_PERMISSIONS (role_id, permission_id) VALUES 
(4, 1),   -- project read
(4, 4), (4, 5),   -- wbs read/write
(4, 7),   -- personnel read
(4, 10), (4, 11),   -- reports read/write
(4, 14),   -- announcements read
(4, 17),   -- duty read
(4, 20),   -- attendance read
(4, 28);   -- dashboard read

-- Safety Permissions - ID 5
INSERT INTO ROLE_PERMISSIONS (role_id, permission_id) VALUES 
(5, 1),   -- project read
(5, 4),   -- wbs read
(5, 7), (5, 8),   -- personnel read/write
(5, 10), (5, 11),   -- reports read/write
(5, 14), (5, 15),   -- announcements read/write
(5, 17), (5, 18),   -- duty read/write
(5, 20), (5, 21),   -- attendance read/write
(5, 23),   -- users read
(5, 25),   -- roles read
(5, 28);   -- dashboard read

COMMIT;

-- Verify permission data insertion
SELECT 'Permissions' as table_name, COUNT(*) as record_count FROM PERMISSIONS
UNION ALL
SELECT 'Role_Permissions', COUNT(*) FROM ROLE_PERMISSIONS;

-- Show role-permission summary
SELECT r.name as role_name, COUNT(rp.permission_id) as permission_count
FROM ROLES r
LEFT JOIN ROLE_PERMISSIONS rp ON r.id = rp.role_id
GROUP BY r.id, r.name
ORDER BY r.id;