-- PCM Project Seed Data
-- This script inserts comprehensive test data for development and testing

-- Clear existing data (for development purposes)
DELETE FROM ATTENDANCE;
DELETE FROM DUTY_ROSTERS;
DELETE FROM ANNOUNCEMENTS;
DELETE FROM REPORT_ATTACHMENTS;
DELETE FROM DAILY_REPORTS;
DELETE FROM WBS_CHANGE_LOGS;
DELETE FROM WBS_ITEMS;
DELETE FROM PERSONNEL;
DELETE FROM SUBCONTRACTORS;
DELETE FROM USER_ROLES;
DELETE FROM ROLES;
DELETE FROM PROJECTS;
DELETE FROM USERS;

-- Reset sequences
ALTER TABLE USERS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE PROJECTS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE ROLES MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE USER_ROLES MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE SUBCONTRACTORS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE PERSONNEL MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE WBS_ITEMS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE WBS_CHANGE_LOGS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE DAILY_REPORTS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE REPORT_ATTACHMENTS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE ANNOUNCEMENTS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE DUTY_ROSTERS MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE ATTENDANCE MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

-- Insert Roles
INSERT INTO ROLES (name, description) VALUES ('PM', '專案經理 - 負責專案整體管理');
INSERT INTO ROLES (name, description) VALUES ('QC', '品管人員 - 負責品質控制與檢查');
INSERT INTO ROLES (name, description) VALUES ('Supervisor', '工地主任 - 負責現場監督管理');
INSERT INTO ROLES (name, description) VALUES ('Engineer', '工程師 - 負責技術支援');
INSERT INTO ROLES (name, description) VALUES ('Safety', '安全管理員 - 負責工地安全管理');

-- Insert Users (passwords are hashed version of 'password123')
INSERT INTO USERS (username, hashed_password, full_name, email) VALUES 
('pm.chen', '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '陳志明', 'chen.pm@pcm.com');

INSERT INTO USERS (username, hashed_password, full_name, email) VALUES 
('qc.wang', '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '王美惠', 'wang.qc@pcm.com');

INSERT INTO USERS (username, hashed_password, full_name, email) VALUES 
('sup.lin', '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '林建志', 'lin.sup@pcm.com');

INSERT INTO USERS (username, hashed_password, full_name, email) VALUES 
('eng.lee', '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '李怡君', 'lee.eng@pcm.com');

INSERT INTO USERS (username, hashed_password, full_name, email) VALUES 
('safety.huang', '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '黃安全', 'huang.safety@pcm.com');

INSERT INTO USERS (username, hashed_password, full_name, email) VALUES 
('pm.wu', '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '吳國強', 'wu.pm@pcm.com');

INSERT INTO USERS (username, hashed_password, full_name, email) VALUES 
('qc.chou', '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '周品質', 'chou.qc@pcm.com');

INSERT INTO USERS (username, hashed_password, full_name, email) VALUES 
('admin', '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '系統管理員', 'admin@pcm.com');

-- Insert Projects
INSERT INTO PROJECTS (name, code, status, start_date, planned_submission_date, total_duration_days) VALUES 
('台北捷運環狀線工程', 'MRT-CIRCLE-2024', '進行中', DATE '2024-01-15', DATE '2025-12-31', 715);

INSERT INTO PROJECTS (name, code, status, start_date, planned_submission_date, total_duration_days) VALUES 
('高雄港區開發案', 'KH-PORT-2024', '進行中', DATE '2024-03-01', DATE '2025-08-30', 547);

INSERT INTO PROJECTS (name, code, status, start_date, planned_submission_date, total_duration_days) VALUES 
('桃園機場第三航廈', 'TPE-T3-2024', '準備中', DATE '2024-06-01', DATE '2026-05-31', 730);

INSERT INTO PROJECTS (name, code, status, start_date, planned_submission_date, total_duration_days) VALUES 
('台中水湳智慧城', 'TC-SMART-2024', '進行中', DATE '2024-02-15', DATE '2025-11-15', 639);

-- Insert User Roles (assign users to projects with specific roles)
-- Project 1: 台北捷運環狀線工程
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (1, 1, 1); -- 陳志明 as PM
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (2, 2, 1); -- 王美惠 as QC
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (3, 3, 1); -- 林建志 as Supervisor
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (5, 5, 1); -- 黃安全 as Safety

-- Project 2: 高雄港區開發案
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (6, 1, 2); -- 吳國強 as PM
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (7, 2, 2); -- 周品質 as QC
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (4, 4, 2); -- 李怡君 as Engineer

-- Project 3: 桃園機場第三航廈
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (1, 1, 3); -- 陳志明 as PM (multi-project)
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (2, 2, 3); -- 王美惠 as QC (multi-project)

-- Project 4: 台中水湳智慧城
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (6, 1, 4); -- 吳國強 as PM (multi-project)
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (4, 4, 4); -- 李怡君 as Engineer (multi-project)

-- Admin role (can access all projects)
INSERT INTO USER_ROLES (user_id, role_id, project_id) VALUES (8, 1, NULL); -- Admin with PM role globally

-- Insert Subcontractors
INSERT INTO SUBCONTRACTORS (name, contact_person, phone, email, address) VALUES 
('大昌營造股份有限公司', '劉大昌', '02-2345-6789', 'contact@dachang.com.tw', '台北市信義區信義路五段7號');

INSERT INTO SUBCONTRACTORS (name, contact_person, phone, email, address) VALUES 
('正豐建設有限公司', '張正豐', '07-345-6789', 'info@zhengfeng.com.tw', '高雄市前鎮區中山四路100號');

INSERT INTO SUBCONTRACTORS (name, contact_person, phone, email, address) VALUES 
('永安工程股份有限公司', '李永安', '03-456-7890', 'service@yongan.com.tw', '桃園市中壢區中正路200號');

INSERT INTO SUBCONTRACTORS (name, contact_person, phone, email, address) VALUES 
('協力機電有限公司', '陳協力', '04-567-8901', 'help@xieli.com.tw', '台中市西屯區台灣大道三段300號');

-- Insert Personnel
INSERT INTO PERSONNEL (subcontractor_id, name, position, phone, email, employee_id) VALUES 
(1, '劉小明', '工地主任', '0912-345-678', 'liu.xiaoming@dachang.com.tw', 'DC001');

INSERT INTO PERSONNEL (subcontractor_id, name, position, phone, email, employee_id) VALUES 
(1, '陳大華', '技師', '0923-456-789', 'chen.dahua@dachang.com.tw', 'DC002');

INSERT INTO PERSONNEL (subcontractor_id, name, position, phone, email, employee_id) VALUES 
(1, '王志強', '工人', '0934-567-890', 'wang.zhiqiang@dachang.com.tw', 'DC003');

INSERT INTO PERSONNEL (subcontractor_id, name, position, phone, email, employee_id) VALUES 
(2, '張美玲', '品管師', '0945-678-901', 'zhang.meiling@zhengfeng.com.tw', 'ZF001');

INSERT INTO PERSONNEL (subcontractor_id, name, position, phone, email, employee_id) VALUES 
(2, '李建成', '安全管理員', '0956-789-012', 'li.jiancheng@zhengfeng.com.tw', 'ZF002');

INSERT INTO PERSONNEL (subcontractor_id, name, position, phone, email, employee_id) VALUES 
(3, '林志豪', '機電工程師', '0967-890-123', 'lin.zhihao@yongan.com.tw', 'YA001');

INSERT INTO PERSONNEL (subcontractor_id, name, position, phone, email, employee_id) VALUES 
(4, '黃智慧', '系統工程師', '0978-901-234', 'huang.zhihui@xieli.com.tw', 'XL001');

-- Insert WBS Items for Project 1 (台北捷運環狀線工程)
INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(1, NULL, '1', '台北捷運環狀線工程', '整體專案', 1, 1);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(1, 1, '1.1', '規劃設計階段', '前期規劃與詳細設計', 2, 1);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(1, 1, '1.2', '土建工程', '隧道挖掘與車站建設', 2, 2);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(1, 1, '1.3', '機電系統', '軌道、電力、通訊系統', 2, 3);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(1, 2, '1.1.1', '環境影響評估', '環評作業', 3, 1);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(1, 2, '1.1.2', '細部設計', '工程細部設計', 3, 2);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(1, 3, '1.2.1', '隧道工程', '主線隧道挖掘', 3, 1);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(1, 3, '1.2.2', '車站工程', '各車站建設', 3, 2);

-- Insert some WBS items for other projects
INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(2, NULL, '2', '高雄港區開發案', '整體專案', 1, 1);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(2, 9, '2.1', '港區規劃', '港區整體規劃', 2, 1);

INSERT INTO WBS_ITEMS (project_id, parent_id, code, name, description, level_number, sort_order) VALUES 
(2, 9, '2.2', '基礎建設', '港區基礎設施建設', 2, 2);

-- Insert Daily Reports
INSERT INTO DAILY_REPORTS (project_id, reported_by, report_date, content, weather, progress_notes, issues) VALUES 
(1, 1, DATE '2024-09-08', '今日進行隧道挖掘作業，完成50公尺進度', '晴天', '按計畫進行，無重大問題', '地質較硬，挖掘速度略慢');

INSERT INTO DAILY_REPORTS (project_id, reported_by, report_date, content, weather, progress_notes, issues) VALUES 
(1, 3, DATE '2024-09-07', '車站A1施工進度報告', '多雲', '鋼筋綁紮完成80%', '混凝土供應商延遲交貨');

INSERT INTO DAILY_REPORTS (project_id, reported_by, report_date, content, weather, progress_notes, issues) VALUES 
(2, 6, DATE '2024-09-08', '港區碼頭工程進度', '晴天', '第一期工程完成60%', '無');

-- Insert Announcements
INSERT INTO ANNOUNCEMENTS (project_id, title, content, created_by, is_active, priority) VALUES 
(1, '安全警示：隧道作業注意事項', '請所有作業人員務必配戴安全帽，並注意通風系統運作狀況。如發現異常請立即回報。', 5, 1, 'high');

INSERT INTO ANNOUNCEMENTS (project_id, title, content, created_by, is_active, priority) VALUES 
(1, '每週例會通知', '本週例會將於週五下午2點在現場辦公室舉行，請相關人員準時參加。', 1, 1, 'normal');

INSERT INTO ANNOUNCEMENTS (project_id, title, content, created_by, is_active, priority) VALUES 
(2, '材料進場時間調整', '因應供應商配送時間調整，本週材料進場時間改為每日上午8點開始。', 6, 1, 'normal');

INSERT INTO ANNOUNCEMENTS (project_id, title, content, created_by, is_active, priority) VALUES 
(NULL, '系統維護通知', '系統將於本週日凌晨2-4點進行維護，期間可能影響登入功能。', 8, 1, 'high');

-- Insert Duty Rosters
INSERT INTO DUTY_ROSTERS (project_id, personnel_id, duty_date, shift_type, notes) VALUES 
(1, 1, DATE '2024-09-09', 'day', '正常值班');

INSERT INTO DUTY_ROSTERS (project_id, personnel_id, duty_date, shift_type, notes) VALUES 
(1, 2, DATE '2024-09-09', 'night', '夜班巡檢');

INSERT INTO DUTY_ROSTERS (project_id, personnel_id, duty_date, shift_type, notes) VALUES 
(1, 3, DATE '2024-09-10', 'day', '正常值班');

INSERT INTO DUTY_ROSTERS (project_id, personnel_id, duty_date, shift_type, notes) VALUES 
(2, 4, DATE '2024-09-09', 'day', '品管檢查');

INSERT INTO DUTY_ROSTERS (project_id, personnel_id, duty_date, shift_type, notes) VALUES 
(2, 5, DATE '2024-09-09', 'day', '安全巡視');

-- Insert Attendance Records
INSERT INTO ATTENDANCE (personnel_id, project_id, check_in_time, check_out_time, work_date, hours_worked, work_type) VALUES 
(1, 1, TIMESTAMP '2024-09-08 08:00:00', TIMESTAMP '2024-09-08 17:30:00', DATE '2024-09-08', 8.5, '現場管理');

INSERT INTO ATTENDANCE (personnel_id, project_id, check_in_time, check_out_time, work_date, hours_worked, work_type) VALUES 
(2, 1, TIMESTAMP '2024-09-08 08:15:00', TIMESTAMP '2024-09-08 17:15:00', DATE '2024-09-08', 8.0, '技術作業');

INSERT INTO ATTENDANCE (personnel_id, project_id, check_in_time, check_out_time, work_date, hours_worked, work_type) VALUES 
(3, 1, TIMESTAMP '2024-09-08 08:30:00', TIMESTAMP '2024-09-08 17:00:00', DATE '2024-09-08', 7.5, '施工作業');

INSERT INTO ATTENDANCE (personnel_id, project_id, check_in_time, check_out_time, work_date, hours_worked, work_type) VALUES 
(4, 2, TIMESTAMP '2024-09-08 08:00:00', TIMESTAMP '2024-09-08 17:30:00', DATE '2024-09-08', 8.5, '品管檢驗');

INSERT INTO ATTENDANCE (personnel_id, project_id, check_in_time, check_out_time, work_date, hours_worked, work_type) VALUES 
(5, 2, TIMESTAMP '2024-09-08 07:45:00', TIMESTAMP '2024-09-08 17:45:00', DATE '2024-09-08', 9.0, '安全管理');

-- Insert some WBS Change Logs
INSERT INTO WBS_CHANGE_LOGS (wbs_item_id, changed_by, change_type, old_value, new_value, change_reason) VALUES 
(7, 1, 'UPDATE', '隧道挖掘', '主線隧道挖掘', '名稱更加明確');

INSERT INTO WBS_CHANGE_LOGS (wbs_item_id, changed_by, change_type, old_value, new_value, change_reason) VALUES 
(8, 1, 'UPDATE', '車站建設', '各車站建設', '涵蓋範圍說明');

COMMIT;

-- Verify data insertion
SELECT 'Users' as table_name, COUNT(*) as record_count FROM USERS
UNION ALL
SELECT 'Projects', COUNT(*) FROM PROJECTS
UNION ALL
SELECT 'Roles', COUNT(*) FROM ROLES
UNION ALL
SELECT 'User_Roles', COUNT(*) FROM USER_ROLES
UNION ALL
SELECT 'Subcontractors', COUNT(*) FROM SUBCONTRACTORS
UNION ALL
SELECT 'Personnel', COUNT(*) FROM PERSONNEL
UNION ALL
SELECT 'WBS_Items', COUNT(*) FROM WBS_ITEMS
UNION ALL
SELECT 'Daily_Reports', COUNT(*) FROM DAILY_REPORTS
UNION ALL
SELECT 'Announcements', COUNT(*) FROM ANNOUNCEMENTS
UNION ALL
SELECT 'Duty_Rosters', COUNT(*) FROM DUTY_ROSTERS
UNION ALL
SELECT 'Attendance', COUNT(*) FROM ATTENDANCE
UNION ALL
SELECT 'WBS_Change_Logs', COUNT(*) FROM WBS_CHANGE_LOGS;